### PR TITLE
Input validation

### PR DESCRIPTION
**Pull request by ChloeDickison**
All fields have been validated to ensure they are filled in and are filled in with the correct data type. Error messages show up for all errors that occur and bring the user back to the primary page instead of going to results. In the future, it would be helpful to determine how to save the user's input in the fields they inputted correctly so they don't have to start over. Copy was changed from 'doses' to 'vials' for the number of doses and dose type - easy change back if that's not agreed on, it didn't make sense to me to be saying what dose type the vial is and asking how many doses are available as that requires math from the user (ie. if they have 10 5 dose vials they have 50 doses). Further validation can occur if we need to (ie. making sure a number is between x-y, etc). 

To Test:
- Try to 'Go to results' with no input, you should have an error message for every field, plus an additional error message prompting correct input where applicable. This should total 12 pop-ups. NOTE: you will not receive an error message for not putting in the time unless you select 'yes' for terminating service
- Input anything except for numbers in the text fields, you should get pop-ups telling you the correct data type
- Select 'yes' to terminate service and try leaving the time field blank, you should get a pop-up asking to input the time and to input the time in the correct format
- Select 'yes' to terminate service and try putting text in the time field, you should get a pop-up asking to input the time in the correct format
- Select 'yes' to terminate service and try putting various numbers in the incorrect format in the time field (ie. 123345, 12, etc), you should get a pop-up asking to input the time in the correct format. NOTE: Currently it will accept 14:00, but also 1400, let me know if that's an issue.
- Select all drop downs and 'yes' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console
- Select all drop downs and 'no' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console

### CODE REVIEW

**Comment by ddanelon** [comment]
I'm unfortunately having issues trying to test this. Whenever a pop-up is supposed to appear after selecting "See Results", it indicates that it's loading and never stops loading.

**Comment by zsnahmia** [comment]
Got the same issue as Deanna for the case with no inputs and just clicking See Results directly

**Comment by rm3shah** [comment]
Hi, I was able to run the code and popups are showing up but there are a few missing test cases and wording changes I'd like to suggest. Items with a checkmark indicate the test passed.

- [ ] 1. Try to 'Go to results' with no input, you should have an error message for every field, plus an additional error message prompting correct input where applicable. This should total 12 pop-ups. NOTE: you will not receive an error message for not putting in the time unless you select 'yes' for terminating service
- [ ] 2. Input anything except for numbers in the text fields, you should get pop-ups telling you the correct data type
- [ ] 3. Select 'yes' to terminate service and try leaving the time field blank, you should get a pop-up asking to input the time and to input the time in the correct format
- [ ] 4. Select 'yes' to terminate service and try putting text in the time field, you should get a pop-up asking to input the time in the correct format
- [ ] 5. Select 'yes' to terminate service and try putting various numbers in the incorrect format in the time field (ie. 123345, 12, etc), you should get a pop-up asking to input the time in the correct format. NOTE: Currently it will accept 14:00, but also 1400, let me know if that's an issue.
- [ ] 6. Select all drop downs and 'yes' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console
- [ ] 7. Select all drop downs and 'no' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console


Cases that are missing:
1. Users are able to select the same vial size for both vial types without an error prompt
2. Users are able to input a time to terminate service when they select 'no' to termination of service
3. Users are able to input negative integers for all text fields (including time field)
4. Users are able to enter special characters in text input fields so long as there is an integer present (i.e., -1^4, 5#7)

Weird behaviour/other things to consider:
1. Tabbing between input fields is not in order 
2. If a user inputs all values correctly expect for filling out a vial type and number of vials for that type the user is prompted with 3 popup errors (shouldn't this be 2?)
3. The form is cleared as soon as 'see results' is clicked so if there was an error in user input, they have to re-enter their information 
4. I find the error prompts to be really demanding, could we reword them to be "please enter a number..." 
5. Users are not shown or aware of what "input dose type 1" is (it would be nice to highlight or put a red outline around fields with issues)

This is a lot to tackle and probably deserves another ticket in the next sprint. I would suggest that more people QA because there are probably other cases that we need to handle.

**Comment by brandonrhayes** [comment]
**Validation**
- [ ] 1. Try to 'Go to results' with no input, you should have an error message for every field, plus an additional error message prompting correct input where applicable. This should total 12 pop-ups. NOTE: you will not receive an error message for not putting in the time unless you select 'yes' for terminating service
- [ ] 2. Input anything except for numbers in the text fields, you should get pop-ups telling you the correct data type
 - [ ] 3. Select 'yes' to terminate service and try leaving the time field blank, you should get a pop-up asking to input the time and to input the time in the correct format
 - [ ] 4. Select 'yes' to terminate service and try putting text in the time field, you should get a pop-up asking to input the time in the correct format
 - [ ] 5. Select 'yes' to terminate service and try putting various numbers in the incorrect format in the time field (ie. 123345, 12, etc), you should get a pop-up asking to input the time in the correct format. NOTE: Currently it will accept 14:00, but also 1400, let me know if that's an issue.
- [ ] 6. Select all drop downs and 'yes' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console
 - [ ] 7. Select all drop downs and 'no' for the radio button and fill in text fields correctly, you should be taken to the results page and have all data outputted to the console

**Extending on Remi's list:**

**Additional Notes:**
1. The default sizing of the module should be full screen or at least not require expanding to see all fields.
2.

**Pull request closed without merging**
