### PR TITLE
Refine tabbing behaviour of GUI, field updates, and error alerts set-up

### PR DESCRIPTION
**Pull request by ddanelon**
What's changed:

- Removed "expected demand" input from GUI
- Removed "time to terminate service" input from GUI
- Added "days remaining in replenishment cycle" to GUI
- Updated copy from "Dose type" to "Vial type" and "Number of doses" to "Number of vials"
- Fixed tabbing behaviour to tab in order
- Created an alert to show if first or second dropdown are not selected > Chloe to complete the input validation

How to test:

- Validate existing functionality still works
- Test that alert shows when first/second dropdown not selected
- Test tabbing is in order

Optional:

- Confirm replenishment cycle copy makes sense

Thanks team!

### CODE REVIEW

**Review by brandonrhayes — CHANGES_REQUESTED** [review]
Requesting changes because it looks like this branch is out of date with develop.  There will be merge conflicts unless you pull in these changes from develop.

Verified as requested otherwise and changes look great!  
How to test:
- [x] Validate existing functionality still works
- [x] Test that alert shows when first/second dropdown not selected
- [x] Test tabbing is in order `NOTE: The tabbing changes are awesome!  This makes the form so much quicker to use.`

Optional:
- [ ] Confirm replenishment cycle copy makes sense `NOTE: not entirely sure what you mean by this one, if you mean the new added box, then yes.  The tool tips will be helpful in  making these clear to any user. However, perhaps this should be reworded to: "How many days remain until your next expected replenishment of this vaccine?`

A few other recommendations for consideration (may include duplications of things I've mentioned before):

- _PRIMARY INPUTS_  should likely be renamed to require inputs
- The _See Results_ button should likely be renamed to "Run Model and Show Results",

**Comment by ddanelon** [comment]
@brandonrhayes thanks for your review! Below is my response to your comments, not all need to be address in this PR.

Regarding the branch being out of date with develop:
1. How did you know that? Curious because I didn't see (or missed) that kind of notification on my end, so I'd like to learn how to spot that in the future.
2. How do you resolve this? I went into my branch and pulled from the origin, is that all that needs to be done?

Regarding the optional test to "Confirm replenishment cycle copy makes sense", you interpreted my question correctly. I've reworded the text to say "How many days remaining until next vaccine replenishment?".

Regarding your recommendations:
1. Updated title from "primary inputs" to "required inputs", I agree this makes more sense from a user standpoint.
2. Chose to leave the "See Results" button as is as I think this will make more sense to the user, I'd like to keep it simple. Definitely something we can discuss with the team if needed.

**Review by brandonrhayes — COMMENTED** [review]
Looks good now, Deanna!

**Review by zsnahmia — APPROVED** [review]
Hey Deanna - tested what you requested and looks good from my end. The dropdowns are also completely accessible using keyboard navigation (using tab/enter/down arrow to navigate and make selections) - which is awesome!

Just noting that I am not seeing the 'Required Inputs' copy and am still seeing Primary Inputs. maybe you didn't commit these changes here? We can also just change them later - no big deal.

**Review by brandonrhayes — APPROVED** [review]

**Comment by brandonrhayes** [comment]
Looks fine from a high-level. Approving changes based on Zoe's comments and review. OK to merge.

**Pull request merged**
