### PR TITLE
Hover action implementation for field explanations

### PR DESCRIPTION
**Pull request by zsnahmia**
Hey team, adding Chloe and Deanna as reviewers to allow us to check across Mac/PC compatibility

This PR contains the following and was a combined effort from me and Deanna :)
1. Implementation of hover actions for the field explanations. note that clicking the question mark icons does not make the explanations appear, they will only appear upon hovering over the icon
2. Styling updates for the fields to make the GUI a bit prettier

Please ensure the following
1. Existing functionality prior to this PR is still functional
2. No styling issues on your devices - i.e. text getting cut off etc
3. All tooltips are functional, and the copy makes sense to each of you. Note that I had to write something new for the remaining days in the cycle cuz thats a new thing we didn't have in the GUI before. let me know what you guys think about what I wrote, we can also add more detail!

Thank yaaaaaa!

### CODE REVIEW

**Comment by brandonrhayes** [comment]
Took a look at this!  I like the colour changes!

I am not seeing the hover actions on PC. UPDATE! I am... However, there appears to be a 3 second delay before it pops up. So it appears broken.
SlowResponseOnHoover

All hoover functions otherwise are working. Perhaps if this is an issue, since we are using (?) buttons, we could click them to see this pop-up instead? I personally tried clicking it at first when the hoover didn't work immediately and then was like what the heck nope not working on windows.

Also, perhaps we should add a max to the number of vial fields...
WrappingNumbersHard

**Comment by ddanelon** [comment]
GUI is a bit squished on my end. Going to fix and commit and then Chloe can validate the GUI looks normal on her end.
image

**Comment by ddanelon** [comment]
Pushed my commit with my GUI updates making it less squished on my end. @ChloeDickison please confirm when you review that the GUI looks like the attached image.

Additionally, I was able to validate the following tests:

- [x] Existing functionality prior to this PR is still functional
- [x] No styling issues on your devices - i.e. text getting cut off etc > No styling issues after update
- [x] All tooltips are functional, and the copy makes sense to each of you. Note that I had to write something new for the remaining days in the cycle cuz thats a new thing we didn't have in the GUI before. let me know what you guys think about what I wrote, we can also add more detail!

Feedback: 

- Everything works exactly as expected! 
- Really love the design updates, looks awesome
- I think the tooltip copies are too long, something we should re-evaluate in the future

I'm not going to approve since I worked on this PR.

image

**Review by ChloeDickison — APPROVED** [review]
I think everything works well enough to satisfy the requirements and merge, however, I did find some usability issues that we may want to look into in a future ticket:

1) I am also experiencing a delay of a few second when hovering, it's not a huge deal but definitely not the best experience and also made me think that I was supposed to click on the button and not hover
2) The copy should probably be revisited to make it shorter and more succinct. It's definitely more noticeable now that it's implemented how long it is -> maybe we should set a character limit and then revisit the copy to try to get it under that character limit
3) The hover goes away after a certain period of time, so with the current copy, I actually couldn't read it all before the hover went away. Is this a setting that's been set to disappear or just how the hovering works?

Love the styling change and everything looks great for me on pc :)

**Pull request merged**
